pipeline {
    agent none
    parameters {
        choice(
            name: 'PROTOCOL', 
            choices: ['fixbb', 'binder', 'hallucination'], 
            description: '')
        file(name: 'MY_FILE', description: 'Upload your file')
    }
    stages {
        stage('Run colabdesign') {
            agent {
                label "gpu-cloud"
            }
            environment {
            }
            steps {
                sh 'run.sh'
            }
        }
        stage('Wait for completion'){
            agent {
                label "gpu"
            }
            environment {
                USER_PASS_SECRET = credentials('suraj-jenkins-password')
                POSTGRES_PASSWORD = credentials('ld_etc_db_gcs')
            }
            steps {
                sh "sleep 16h"
            }
        }
        stage('Collect results') {
            agent {
                label "docker-cloud"
            }
            environment {
                USER_PASS_SECRET = credentials('suraj-jenkins-password')
                POSTGRES_PASSWORD = credentials('ld_etc_db_gcs')
            }
            steps {
                sh 'rm -rf results'
                sh 'mkdir -p results'
                sh 'chmod +x ./scripts/dashboard_backtest/collect_results.sh'
                sh './scripts/dashboard_backtest/collect_results.sh'
                sh 'tar -czf results.tar.gz results'
            }
            post {
                always {
                    archiveArtifacts artifacts: 'results.tar.gz', onlyIfSuccessful: true
                    emailext attachLog: true,
                    body: '$DEFAULT_CONTENT',
                        to: 'suraj.gattani@schrodinger.com',
                        recipientProviders: [],
                        subject: '${JOB_NAME}-${BUILD_NUMBER}'
                }
            }
        }
    }
}
